import './globals.css';
import type { Metadata } from 'next';
import { Providers } from './providers';
import AppNavbar from '@/components/AppNavbar';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'WildLine Detailing',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark scroll-smooth">
      <body className="overflow-x-hidden w-screen block">
        <Providers>
          <AppNavbar></AppNavbar>
          {children}
          <Footer></Footer>
        </Providers>
      </body>
    </html>
  );
}
